### ISSUE TITLE
Publish a new version on Pypi

### ISSUE THREAD

**Issue by ZeFr3d** [haintd/python-kongclient#2]
Hi,

I've started to use this package and it's very convenient (and a time saver), thank you!

However, I've encountered an issue with exception handling while extending it to add few features for our needs.
The good news is that the issue has already been fixed in https://github.com/haintd/python-kongclient/pull/1 :)

Could you please release a new version on Pypi (1.1.1?) to include this fix?

Thank you

**Comment by tniah** [comment]
I'm done.
Thank you.

**Comment by ZeFr3d** [comment]
Thank you!
